#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi
for FILE in `git diff-index --name-status $against -- | grep -E '^[AUM].*\.(cpp|h|inl)$'| cut -c3-`; do
	"/c/Program Files (x86)\AStyle\bin\AStyle.exe" --suffix=none --mode=c --pad-paren-in --add-brackets --indent=tab=4 -A1 $FILE
	git add $FILE
done
